const Contryname = {
  Afghanistan: "Afghanistan",
  AlandIslands: "Aland Islands",
  Albania: "Albania",
  Algeria: "Algeria",
  AmericanSamoa: "American Samoa",
  Andorra: "Andorra",
  Angola: "Angola",
  Anguilla: "Anguilla",
  AntiguaandBarbuda: "Antigua and Barbuda",
  Argentina: "Argentina",
  Armenia: "Armenia",
  Aruba: "Aruba",
  Australia: "Australia",
  Austria: "Austria",
  Azerbaijan: "Azerbaijan",
  BahamasThe: "Bahamas, The",
  Bahrain: "Bahrain",
  Bangladesh: "Bangladesh",
  Barbados: "Barbados",
  Belarus: "Belarus",
  Belgium: "Belgium",
  Belize: "Belize",
  Benin: "Benin",
  Bermuda: "Bermuda",
  Bhutan: "Bhutan",
  Bolivia: "Bolivia",
  BonaireSaintEustatiuandSaba: "Bonaire, Saint Eustatius and Saba",
  BosniaandHerzegovina: "Bosnia and Herzegovina",
  Botswana: "Botswana",
  BouvetIsland: "Bouvet Island",
  Brazil: "Brazil",
  BritishIndianOceanTerritory: "British Indian Ocean Territory",
  BruneiDarussalam: "Brunei Darussalam",
  Bulgaria: "Bulgaria",
  BurkinaFaso: "Burkina Faso",
  Burundi: "Burundi",
  Cambodia: "Cambodia",
  Cameroon: "Cameroon",
  Canada: "Canada",
  CapeVerde: "Cape Verde",
  CaymanIslands: "Cayman Islands",
  CentralAfricanRepublic: "Central African Republic",
  Chad: "Chad",
  Chile: "Chile",
  China: "China",
  ChristmasIsland: "Christmas Island",
  CocosKeelingIslands: "Cocos (Keeling) Islands",
  Colombia: "Colombia",
  Comoros: "Comoros",
  Congo: "Congo",
  CongoTheDemocraticRepublicofthe: "Congo, The Democratic Republic of the",
  CookIslands: "Cook Islands",
  CostaRica: "Costa Rica",
  CoteDivoire: "Cote D'ivoire",
  Croatia: "Croatia",
  Curaçao: "Curaçao",
  Cyprus: "Cyprus",
  CzechRepublic: "Czech Republic",
  Denmark: "Denmark",
  Djibouti: "Djibouti",
  Dominica: "Dominica",
  DominicanRepublic: "Dominican Republic",
  Ecuador: "Ecuador",
  Egypt: "Egypt",
  ElSalvador: "El Salvador",
  EquatorialGuinea: "Equatorial Guinea",
  Eritrea: "Eritrea",
  Estonia: "Estonia",
  Ethiopia: "Ethiopia",
  FalklandIslandsMalvinas: "Falkland Islands (Malvinas)",
  FaroeIslands: "Faroe Islands",
  Fiji: "Fiji",
  Finland: "Finland",
  France: "France",
  FrenchGuiana: "French Guiana",
  FrenchPolynesia: "French Polynesia",
  FrenchSouthernTerritories: "French Southern Territories",
  Gabon: "Gabon",
  GambiaThe: "Gambia, The",
  Georgia: "Georgia",
  Germany: "Germany",
  Ghana: "Ghana",
  Gibraltar: "Gibraltar",
  Greece: "Greece",
  Greenland: "Greenland",
  Grenada: "Grenada",
  Guadeloupe: "Guadeloupe",
  Guatemala: "Guatemala",
  Guernsey: "Guernsey",
  Guinea: "Guinea",
  GuineaBissau: "Guinea-Bissau",
  Guyana: "Guyana",
  Haiti: "Haiti",
  HeardIslandandtheMcDonaldIslands: "Heard Island and the McDonald Islands",
  HolySee: "Holy See",
  Honduras: "Honduras",
  HongKong: "Hong Kong",
  Hungary: "Hungary",
  Iceland: "Iceland",
  India: "India",
  Indonesia: "Indonesia",
  Iraq: "Iraq",
  Ireland: "Ireland",
  IsleofMan: "Isle of Man",
  Israel: "Israel",
  Italy: "Italy",
  Jamaica: "Jamaica",
  Japan: "Japan",
  Jersey: "Jersey",
  Jordan: "Jordan",
  Kazakhstan: "Kazakhstan",
  Kenya: "Kenya",
  Kiribati: "Kiribati",
  Kosovo: "Kosovo",
  Kuwait: "Kuwait",
  Kyrgyzstan: "Kyrgyzstan",
  LaoPeoplesDemocraticRepublic: "Lao People's Democratic Republic",
  Latvia: "Latvia",
  Lebanon: "Lebanon",
  Lesotho: "Lesotho",
  Liberia: "Liberia",
  Libya: "Libya",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lithuania",
  Luxembourg: "Luxembourg",
  Macao: "Macao",
  MacedoniaTheFormerYugoslavRepublicof:
    "Macedonia, The Former Yugoslav Republic of",
  Madagascar: "Madagascar",
  Malawi: "Malawi",
  Malaysia: "Malaysia",
  Maldives: "Maldives",
  Mali: "Mali",
  Malta: "Malta",
  MarshallIslands: "Marshall Islands",
  Martinique: "Martinique",
  Mauritania: "Mauritania",
  Mauritius: "Mauritius",
  Mayotte: "Mayotte",
  Mexico: "Mexico",
  MicronesiaFederatedStateof: "Micronesia, Federated States of",
  MoldovaRepublicof: "Moldova, Republic of",
  Monaco: "Monaco",
  Mongolia: "Mongolia",
  Montenegro: "Montenegro",
  Montserrat: "Montserrat",
  Morocco: "Morocco",
  Mozambique: "Mozambique",
  Myanmar: "Myanmar",
  Namibia: "Namibia",
  Nauru: "Nauru",
  Nepal: "Nepal",
  Netherlands: "Netherlands",
  NetherlandsAntilles: "Netherlands Antilles",
  NewCaledonia: "New Caledonia",
  NewZealand: "New Zealand",
  Nicaragua: "Nicaragua",
  Niger: "Niger",
  Nigeria: "Nigeria",
  Niue: "Niue",
  NorfolkIsland: "Norfolk Island",
  Norway: "Norway",
  Oman: "Oman",
  Pakistan: "Pakistan",
  Palau: "Palau",
  PalestinianTerritories: "Palestinian Territories",
  Panama: "Panama",
  PapuaNewGuinea: "Papua New Guinea",
  Paraguay: "Paraguay",
  Peru: "Peru",
  Philippines: "Philippines",
  Pitcairn: "Pitcairn",
  Poland: "Poland",
  Portugal: "Portugal",
  Qatar: "Qatar",
  RepublicofKorea: "Republic of Korea",
  Reunion: "Reunion",
  Romania: "Romania",
  RussianFederation: "Russian Federation",
  Rwanda: "Rwanda",
  SaintBarthelemy: "Saint Barthelemy",
  SaintHelenaAscensionandTristandaCunha:
    "Saint Helena, Ascension and Tristan da Cunha",
  SaintKittsandNevis: "Saint Kitts and Nevis",
  SaintLucia: "Saint Lucia",
  SaintMartin: "Saint Martin",
  SaintPierreandMiquelon: "Saint Pierre and Miquelon",
  SaintVincentandtheGrenadines: "Saint Vincent and the Grenadines",
  Samoa: "Samoa",
  SanMarino: "San Marino",
  SaoTomeandPrincipe: "Sao Tome and Principe",
  SaudiArabia: "Saudi Arabia",
  Senegal: "Senegal",
  Serbia: "Serbia",
  Seychelles: "Seychelles",
  SierraLeone: "Sierra Leone",
  Singapore: "Singapore",
  SintMaarten: "Sint Maarten",
  Slovakia: "Slovakia",
  Slovenia: "Slovenia",
  SolomonIslands: "Solomon Islands",
  Somalia: "Somalia",
  SouthAfrica: "South Africa",
  SouthGeorgiaandtheSouthSandwichIslands:
    "South Georgia and the South Sandwich Islands",
  Spain: "Spain",
  SriLanka: "Sri Lanka",
  Suriname: "Suriname",
  SvalbardandJanMayen: "Svalbard and Jan Mayen",
  Swaziland: "Swaziland",
  Sweden: "Sweden",
  Switzerland: "Switzerland",
  Taiwan: "Taiwan",
  Tajikistan: "Tajikistan",
  TanzaniaUnitedRepublicof: "Tanzania, United Republic of",
  Thailand: "Thailand",
  Timorleste: "Timor-leste",
  Togo: "Togo",
  Tokelau: "Tokelau",
  Tonga: "Tonga",
  TrinidadandTobago: "Trinidad and Tobago",
  Tunisia: "Tunisia",
  Turkey: "Turkey",
  Turkmenistan: "Turkmenistan",
  TurksandCaicosIslands: "Turks and Caicos Islands",
  Tuvalu: "Tuvalu",
  Uganda: "Uganda",
  Ukraine: "Ukraine",
  UnitedArabEmirates: "United Arab Emirates",
  UnitedKingdom: "United Kingdom",
  UnitedStatesMinorOutlyingIslands: "United States Minor Outlying Islands",
  Uruguay: "Uruguay",
  Uzbekistan: "Uzbekistan",
  Vanuatu: "Vanuatu",
  Venezuela: "Venezuela",
  Vietnam: "Vietnam",
  VirginIslandsBritish: "Virgin Islands, British",
  WallisandFutuna: "Wallis and Futuna",
  WesternSahara: "Western Sahara",
  Yemen: "Yemen",
  Zambia: "Zambia",
  Zimbabwe: "Zimbabwe",
};
const LanguageList = {
  English: "EN",
  español: "ES",
  العربية: "AR",
  Deutsch: "DE",
  עברית: "HE",
  한국어: "KO",
  português: "PT",
  中文简体: "ZH",
  中文繁體: "ZH",
};
